# Generated by Django 2.2.1 on 2019-09-15 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'banco',
                'verbose_name_plural': 'banco',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=25, verbose_name='Tipo')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.Bank', verbose_name='Banco')),
            ],
            options={
                'verbose_name': 'tarjeta',
                'verbose_name_plural': 'tarjetas',
            },
        ),
        migrations.CreateModel(
            name='CardEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=50, verbose_name='Tarjeta')),
            ],
            options={
                'verbose_name': 'entidad de tarjeta',
                'verbose_name_plural': 'entidad de tarjetas',
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'forma de pago',
                'verbose_name_plural': 'forma de pagos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CashPayment',
            fields=[
                ('paymenttype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payments.PaymentType')),
                ('currency', models.CharField(choices=[('$ ARG', '$ ARG')], default='$ ARG', max_length=10, verbose_name='Moneda')),
            ],
            options={
                'verbose_name': 'efectivo',
                'verbose_name_plural': 'efectivos',
            },
            bases=('payments.paymenttype',),
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('card_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payments.Card')),
            ],
            options={
                'verbose_name': 'tarjeta de crédito',
                'verbose_name_plural': 'tarjeta de créditos',
            },
            bases=('payments.card',),
        ),
        migrations.CreateModel(
            name='CurrentPayment',
            fields=[
                ('paymenttype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payments.PaymentType')),
                ('paid_out', models.BooleanField(default=False, verbose_name='Cuenta Corriente')),
            ],
            options={
                'verbose_name': 'cuenta corriente',
                'verbose_name_plural': 'cuentas corrientes',
            },
            bases=('payments.paymenttype',),
        ),
        migrations.CreateModel(
            name='DebitCard',
            fields=[
                ('card_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payments.Card')),
            ],
            options={
                'verbose_name': 'tarjeta de débito',
                'verbose_name_plural': 'tarjeta de débitos',
            },
            bases=('payments.card',),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Importe')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.PaymentType', verbose_name='Forma de pago')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Sale', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='card',
            name='card_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.CardEntity', verbose_name='Entidad'),
        ),
        migrations.CreateModel(
            name='CardPayment',
            fields=[
                ('paymenttype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payments.PaymentType')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.Card', verbose_name='Tarjeta')),
            ],
            options={
                'verbose_name': 'tarjeta',
                'verbose_name_plural': 'tarjetas',
            },
            bases=('payments.paymenttype',),
        ),
    ]
