# Generated by Django 2.2.1 on 2019-09-05 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('id_card', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('first_name', models.CharField(max_length=210, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=210, verbose_name='Apellido')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('movile', models.CharField(blank=True, max_length=50, null=True, verbose_name='Celular')),
                ('telephone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Address', verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'persona',
                'verbose_name_plural': 'personas',
                'ordering': ['last_name'],
                'abstract': False,
            },
        ),
    ]
