# Generated by Django 2.2.1 on 2019-09-06 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_remove_address_city'),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='address',
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('street', models.CharField(max_length=50, verbose_name='Calle')),
                ('number_street', models.CharField(max_length=18, verbose_name='Número')),
                ('floor', models.CharField(blank=True, max_length=18, null=True, verbose_name='Piso')),
                ('departament', models.CharField(blank=True, max_length=18, null=True, verbose_name='Departamento')),
                ('type_address', models.CharField(choices=[('Residence', 'Residence')], default='Residence', max_length=12, verbose_name='Tipo de residencia')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.City', verbose_name='Ciudad')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Person', verbose_name='persona')),
            ],
            options={
                'verbose_name': 'dirección',
                'verbose_name_plural': 'direcciones',
                'ordering': ['street', 'number_street'],
            },
        ),
    ]
