# Generated by Django 2.2.1 on 2019-09-06 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_auto_20190905_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='id_card',
            field=models.CharField(max_length=30, unique=True, verbose_name='DNI'),
        ),
    ]
