# Generated by Django 2.2.1 on 2019-09-05 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(help_text='Enter a article', max_length=210, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'provincia',
                'verbose_name_plural': 'provincias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('zip_city', models.CharField(blank=True, max_length=30, null=True, verbose_name='Código postal')),
                ('ddn', models.CharField(blank=True, max_length=12, null=True, verbose_name='Característica')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.State')),
            ],
            options={
                'verbose_name': 'ciudad',
                'verbose_name_plural': 'ciudades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('street', models.CharField(max_length=50, verbose_name='Calle')),
                ('number_street', models.CharField(max_length=18, verbose_name='Número')),
                ('floor', models.CharField(blank=True, max_length=18, null=True, verbose_name='Piso')),
                ('departament', models.CharField(blank=True, max_length=18, null=True, verbose_name='Departamento')),
                ('type_address', models.CharField(choices=[('Residence', 'Residence')], default='Residence', max_length=12, verbose_name='Tipo de residencia')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.City', verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'dirección',
                'verbose_name_plural': 'direcciones',
                'ordering': ['street', 'number_street'],
            },
        ),
    ]
