# Generated by Django 2.2.1 on 2019-09-15 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('balances', '0002_auto_20190915_0556'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleWithDailyBalance',
            fields=[
                ('sale_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales.Sale')),
                ('daily_balance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='balances.DailyBalance', verbose_name='Saldo diario')),
            ],
            options={
                'abstract': False,
            },
            bases=('sales.sale',),
        ),
    ]
