# Generated by Django 2.2.4 on 2019-09-22 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_salewithdailybalance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salewithdailybalance',
            options={'verbose_name': 'venta con saldo', 'verbose_name_plural': 'venta con saldos'},
        ),
    ]
