# Generated by Django 2.2.1 on 2019-09-15 08:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('date_balance', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('init_cash', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Caja inicial')),
            ],
            options={
                'verbose_name': 'saldo diario',
                'verbose_name_plural': 'saldos diarios',
                'ordering': ['-date_balance'],
            },
        ),
    ]
